/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package from;

import dao.nhanvienDao;
import helper.shareHelper;
import java.awt.Color;
import java.util.logging.Level;
import java.util.logging.Logger;
import model.nhanvien;

/**
 *
 * @author ADMIN
 */
public class DoiMKJDialog extends javax.swing.JDialog {

    /**
     * Creates new form DoiMKJDialog
     */
    public DoiMKJDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        init();
    }
   
    nhanvienDao dao=new nhanvienDao();
    public void init(){
        this.txtdangnhap.setText(shareHelper.USER.getMaNV());
       
    }
    public void doiMatKhau(){
        this.txtxacnhanmatkhau.setBackground(Color.white);
        this.txtmatkhaucu.setBackground(Color.white);
        String matKhau=new String(txtmatkhaucu.getPassword());
        String matKhauMoi=new String(txtmatkhaumoi.getPassword());
        String xacNhanMKM=new String(txtxacnhanmatkhau.getPassword());
        if(matKhau.equals(shareHelper.USER.getMatKhau())){
            if(matKhauMoi.equals(xacNhanMKM)){
                shareHelper.USER.setMatKhau(matKhauMoi);
                dao.update(shareHelper.USER);
                 helper.dialogHelper.alert(this, "Đổi mật khẩu thành công!!");
                this.dispose();
            }else{
                this.txtxacnhanmatkhau.setBackground(Color.pink);
                helper.dialogHelper.alert(this, "Mật khẩu xác nhận không trùng chính xác");
            }
        }else{
            this.txtmatkhaucu.setBackground(Color.pink);
            helper.dialogHelper.alert(this, "Mật khẩu cũ nhập không chính xác!");
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        lbldoimatkhau = new javax.swing.JLabel();
        lbltendangnhap = new javax.swing.JLabel();
        txtdangnhap = new javax.swing.JTextField();
        lblmatkhaucu = new javax.swing.JLabel();
        txtmatkhaucu = new javax.swing.JPasswordField();
        lblmatkhaumoi = new javax.swing.JLabel();
        lblxacnhanmatkhau = new javax.swing.JLabel();
        txtmatkhaumoi = new javax.swing.JPasswordField();
        txtxacnhanmatkhau = new javax.swing.JPasswordField();
        btnxacnhan = new javax.swing.JButton();
        txthuy = new javax.swing.JButton();

        jButton1.setBackground(new java.awt.Color(51, 51, 255));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Accept.png"))); // NOI18N
        jButton1.setText("Xác nhận");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lbldoimatkhau.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbldoimatkhau.setForeground(new java.awt.Color(255, 51, 51));
        lbldoimatkhau.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbldoimatkhau.setText("ĐỔI MẬT KHẨU");

        lbltendangnhap.setText("Tên đăng nhập");

        txtdangnhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdangnhapActionPerformed(evt);
            }
        });

        lblmatkhaucu.setText("Mật khẩu cũ");

        txtmatkhaucu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtmatkhaucuActionPerformed(evt);
            }
        });

        lblmatkhaumoi.setText("Mật khẩu mới");

        lblxacnhanmatkhau.setText("Xác nhận mật khẩu");

        btnxacnhan.setBackground(new java.awt.Color(51, 51, 255));
        btnxacnhan.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnxacnhan.setForeground(new java.awt.Color(255, 255, 255));
        btnxacnhan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Accept.png"))); // NOI18N
        btnxacnhan.setText("Xác nhận");
        btnxacnhan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnxacnhanActionPerformed(evt);
            }
        });

        txthuy.setBackground(new java.awt.Color(255, 153, 0));
        txthuy.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txthuy.setForeground(new java.awt.Color(255, 255, 255));
        txthuy.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/No.png"))); // NOI18N
        txthuy.setText("Hủy");
        txthuy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txthuyActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(53, 53, 53)
                                .addComponent(lbldoimatkhau, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(lbltendangnhap))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(txtdangnhap, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(lblmatkhaucu)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtmatkhaucu, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtxacnhanmatkhau)
                            .addComponent(txtmatkhaumoi)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblmatkhaumoi)
                                    .addComponent(lblxacnhanmatkhau))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addComponent(btnxacnhan)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txthuy, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(20, 20, 20)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbldoimatkhau, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbltendangnhap)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtdangnhap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblmatkhaucu)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtmatkhaucu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblmatkhaumoi)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtmatkhaumoi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addComponent(lblxacnhanmatkhau)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtxacnhanmatkhau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnxacnhan)
                    .addComponent(txthuy))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtdangnhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdangnhapActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtdangnhapActionPerformed

    private void txtmatkhaucuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtmatkhaucuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtmatkhaucuActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnxacnhanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnxacnhanActionPerformed
        if( helper.utilityHelper.checkNullPass(txtmatkhaucu)&&
            helper.utilityHelper.checkNullPass(txtmatkhaumoi)&&
            helper.utilityHelper.checkNullPass(txtxacnhanmatkhau))
            {     
                doiMatKhau(); 
            }
        
    }//GEN-LAST:event_btnxacnhanActionPerformed
 
    private void txthuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txthuyActionPerformed
           this.dispose();
    }//GEN-LAST:event_txthuyActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DoiMKJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DoiMKJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DoiMKJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DoiMKJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DoiMKJDialog dialog = new DoiMKJDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnxacnhan;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel lbldoimatkhau;
    private javax.swing.JLabel lblmatkhaucu;
    private javax.swing.JLabel lblmatkhaumoi;
    private javax.swing.JLabel lbltendangnhap;
    private javax.swing.JLabel lblxacnhanmatkhau;
    private javax.swing.JTextField txtdangnhap;
    private javax.swing.JButton txthuy;
    private javax.swing.JPasswordField txtmatkhaucu;
    private javax.swing.JPasswordField txtmatkhaumoi;
    private javax.swing.JPasswordField txtxacnhanmatkhau;
    // End of variables declaration//GEN-END:variables
}
